---
- name: Deploy Spring Boot application
  hosts: localhost
  become: true  # No sudo needed for local deployment
  become_user: root  # Optional: specify user

  vars:
    app_dir: "/opt/myapp"
    app_jar: "app.jar"  # Matches your copied filename

  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"  # Sets owner to your current user
        group: "{{ ansible_user_id }}"

    - name: Copy JAR file from workspace
      ansible.builtin.copy:
        src: "/var/jenkins_home/workspace/ansible-deployment/deployments/{{ app_jar }}"
        dest: "{{ app_dir }}/"
        remote_src: true  # File exists on the same machine
        mode: '0644'

    - name: Find and kill existing Java process
      ansible.builtin.shell: |
        pgrep -f "java.*{{ app_dir }}/{{ app_jar }}" || true
      register: running_process
      changed_when: false
      ignore_errors: true

    - name: Terminate existing application
      ansible.builtin.command: "pkill -f 'java.*{{ app_dir }}/{{ app_jar }}'"
      when: running_process.stdout != ""
      ignore_errors: true  # Continue even if no process found

    - name: Start Spring Boot application
      ansible.builtin.shell: |
        nohup java -jar {{ app_dir }}/{{ app_jar }} > {{ app_dir }}/{{ app_log }} 2>&1 &
        sleep 2  # Allow process to start
        pgrep -f "java.*{{ app_dir }}/{{ app_jar }}" || exit 1
      args:
        executable: /bin/bash
      register: app_start
      changed_when: "'started' in app_start.stdout"