---
- name: Deploy Spring Boot JAR locally
  hosts: localhost
  become: false  # No sudo needed for local deployment

  vars:
    jar_name: "ansible-0.0.1-SNAPSHOT.jar"  # Match your actual JAR name
    deploy_dir: "{{ playbook_dir }}/opt/myapp"  # Your target directory

  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy JAR file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../target/{{ jar_name }}"  # Correct relative path
        dest: "{{ deploy_dir }}/"
        remote_src: false  # File exists on control machine (Jenkins)

    - name: Kill existing app process (if any)
      ansible.builtin.shell: |
        pkill -f "java -jar {{ deploy_dir }}/{{ jar_name }}" || true
      changed_when: false  # Don't fail if no process exists

    - name: Start Spring Boot app with nohup
      ansible.builtin.shell: |
        nohup java -jar {{ deploy_dir }}/{{ jar_name }} > {{ deploy_dir }}/app.log 2>&1 &
      async: 10  # Don't wait for completion
      poll: 0